stages:
    - test
    - coverage
    - analysis
    - report

test:
    stage: test
    image: kennethreitz/pipenv
    script:
        - apt-get update -qq
        - pipenv install --dev
        - pipenv run tox

coverage:
    stage: coverage
    image: kennethreitz/pipenv
    artifacts:
        untracked: true
    dependencies:
        - test
    script:
        - apt-get update -qq
        - pipenv install --dev
        - pipenv run make coverage
    only:
        - master

analysis:
    stage: analysis
    image: ciricihq/gitlab-sonar-scanner
    artifacts:
        untracked: true
    dependencies:
        - coverage
    variables:
        SONAR_URL: http://sonar.hubstairs.com
        SONAR_ANALYSIS_MODE: issues
        SONAR_GITLAB_PROJECT_ID: CI_COMMIT_REF_NAME
    script:
        - gitlab-sonar-scanner
    only:
        - master


report:
    stage: report
    image: ciricihq/gitlab-sonar-scanner
    dependencies:
        - analysis
    variables:
        SONAR_URL: http://sonar.hubstairs.com
        SONAR_ANALYSIS_MODE: publish
        SONAR_GITLAB_PROJECT_ID: CI_COMMIT_REF_NAME
    script:
        - gitlab-sonar-scanner
    only:
        - master
